{% set name = "tox-gh" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tox_gh-{{ version }}.tar.gz
  sha256: da422beccbdc5ad5994fe8faf6c193f2d794e957628b052ba23e7fcf9e2e340f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatch-vcs >=0.4
    - hatchling >=1.25
    - pip
  run:
    - python >=3.8
    - tox >=4.18.1

test:
  imports:
    - tox_gh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tox-dev/tox-gh
  summary: Seamless integration of tox into GitHub Actions.
  description: |
    tox-gh is a tox plugin which helps running tox on GitHub Actions with multiple
    different Python versions on multiple workers in parallel.
  dev_url: https://github.com/tox-dev/tox-gh
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Zeitsperre
