{% set name = "tox-gh" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tox_gh-{{ version }}.tar.gz
  sha256: 4ea585f66585b90f5826b1677cfc9453747792a0f9ff83d468603bc17556e07b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs >=0.4
    - hatchling >=1.25
    - pip
  run:
    - python >={{ python_min }}
    - tox >=4.18.1

test:
  imports:
    - tox_gh
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tox-dev/tox-gh
  summary: Seamless integration of tox into GitHub Actions.
  description: |
    tox-gh is a tox plugin which helps running tox on GitHub Actions with multiple
    different Python versions on multiple workers in parallel.
  dev_url: https://github.com/tox-dev/tox-gh
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Zeitsperre
